package com.tecngo.users.entity;

public enum OnboardingStep {
    MAIN_DATA,
    LEGAL_ACCEPTANCE,
    PROFILE_SELFIE,
    IDENTITY_DOCUMENT,
    TECHNICIAN_PROFESSIONAL_PROFILE,
    TECHNICIAN_CERTIFICATE,
    COMPLETED
}
