package com.tecngo.notifications.entity;

public enum NotificationType {
    NEW_REQUEST,
    NEW_QUOTE,
    QUOTE_ACCEPTED,
    REQUEST_ACCEPTED,
    TECHNICIAN_ON_THE_WAY,
    TECHNICIAN_ARRIVED,
    SERVICE_STARTED,
    SERVICE_COMPLETED,
    NEW_CHAT_MESSAGE,
    NEW_RATING,
    SERVICE_STATUS_CHANGED
}
