package com.tecngo.notifications.entity;

public enum NotificationType {
    NEW_REQUEST,
    NEW_QUOTE,
    QUOTE_ACCEPTED,
    QUOTE_REJECTED,
    REQUEST_ACCEPTED,
    TECHNICIAN_ON_THE_WAY,
    TECHNICIAN_ARRIVED,
    SERVICE_STARTED,
    SERVICE_COMPLETED,
    NEW_CHAT_MESSAGE,
    NEW_RATING,
    PAYMENT_PROOF_UPLOADED,
    SERVICE_EVIDENCE_UPLOADED,
    PAYMENT_PROOF_VERIFIED,
    CONTENT_MODERATION_ALERT,
    CHAT_MODERATION_ALERT,
    SERVICE_STATUS_CHANGED,
    LEGAL_ACCEPTANCE_REQUIRED,
    TECHNICIAN_PROFILE_APPROVED
}
