ALTER TABLE notifications
    DROP CONSTRAINT IF EXISTS notifications_type_check;

ALTER TABLE notifications
    ADD CONSTRAINT notifications_type_check CHECK (type IN (
        'NEW_REQUEST', 'NEW_QUOTE', 'QUOTE_ACCEPTED', 'QUOTE_REJECTED',
        'REQUEST_ACCEPTED', 'TECHNICIAN_ON_THE_WAY', 'TECHNICIAN_ARRIVED',
        'SERVICE_STARTED', 'SERVICE_COMPLETED', 'NEW_CHAT_MESSAGE', 'NEW_RATING',
        'PAYMENT_PROOF_UPLOADED', 'SERVICE_EVIDENCE_UPLOADED',
        'PAYMENT_PROOF_VERIFIED', 'SERVICE_STATUS_CHANGED',
        'LEGAL_ACCEPTANCE_REQUIRED'
    ));
